# Datos de relleno

INSERT INTO INFORMACION_BASICA_SOLICITUDES(NOMBRE_BENEFICIARIO, CURP_BENEFICIARIO, ID_SOLICITUD, URGENTE, NUEVO, VULNERABLE, PENDIENTE, SOLICITUD_NOMBRE, DEPARTAMENTO, ORIGEN, AVANCE_SOLICITUD, FECHA)
VALUES ('ALFREDO TALAVERA DE LA IGLESIA', '02750725V', '7304YWG', false, true, false, true, 'levantar mano', 'dpa 1', 'origen 1', '0', '2021-12-07 15:21:21');

INSERT INTO INFORMACION_BASICA_SOLICITUDES(NOMBRE_BENEFICIARIO, CURP_BENEFICIARIO, ID_SOLICITUD, URGENTE, NUEVO, VULNERABLE, PENDIENTE, SOLICITUD_NOMBRE, DEPARTAMENTO, ORIGEN, AVANCE_SOLICITUD, FECHA)
VALUES ('GLORIA ROCHA ASENCIO', '37331153Z', '4697SPH', true, true, false, true, 'escribir', 'dpa 2', 'origen 1', '0', '2020-10-11 15:21:21');

INSERT INTO INFORMACION_BASICA_SOLICITUDES(NOMBRE_BENEFICIARIO, CURP_BENEFICIARIO, ID_SOLICITUD, URGENTE, NUEVO, VULNERABLE, PENDIENTE, SOLICITUD_NOMBRE, DEPARTAMENTO, ORIGEN, AVANCE_SOLICITUD, FECHA)
VALUES ('JUAN JOSE TERUEL ALMAGRO', '69788771D', '5595LAN', false, true, true, true, 'hablar', 'dpa 3', 'origen 2', '0', '2021-12-04 15:21:21');

INSERT INTO INFORMACION_BASICA_SOLICITUDES(NOMBRE_BENEFICIARIO, CURP_BENEFICIARIO, ID_SOLICITUD, URGENTE, NUEVO, VULNERABLE, PENDIENTE, SOLICITUD_NOMBRE, DEPARTAMENTO, ORIGEN, AVANCE_SOLICITUD, FECHA)
VALUES ('MARIA ELENA GARRIDO CASES', '74765204R', '6417MRI', true, true, true, true, 'levantarse', 'dpa 4', 'origen 3', '0', now());

INSERT INTO INFORMACION_BASICA_SOLICITUDES(NOMBRE_BENEFICIARIO, CURP_BENEFICIARIO, ID_SOLICITUD, URGENTE, NUEVO, VULNERABLE, PENDIENTE, SOLICITUD_NOMBRE, DEPARTAMENTO, ORIGEN, AVANCE_SOLICITUD, FECHA)
VALUES ('AITOR OLIVERAS ELIZALDE', '78964533J', '0193EMU', false, true, true, false, 'comer', 'dpa 5', 'origen 4', '0', '2017-11-20 15:21:21');

INSERT INTO INFORMACION_BASICA_SOLICITUDES(NOMBRE_BENEFICIARIO, CURP_BENEFICIARIO, ID_SOLICITUD, URGENTE, NUEVO, VULNERABLE, PENDIENTE, SOLICITUD_NOMBRE, DEPARTAMENTO, ORIGEN, AVANCE_SOLICITUD, FECHA)
VALUES ('ALBERT MOLINERO VALLS', '58622326H', '9936EER', false, true, false, false, 'dormir', 'dpa 6', 'origen 5', '0', now());

INSERT INTO INFORMACION_BASICA_SOLICITUDES(NOMBRE_BENEFICIARIO, CURP_BENEFICIARIO, ID_SOLICITUD, URGENTE, NUEVO, VULNERABLE, PENDIENTE, SOLICITUD_NOMBRE, DEPARTAMENTO, ORIGEN, AVANCE_SOLICITUD, FECHA)
VALUES ('ESPERANZA OLIVARES VILLALOBOS', '00830497J', '7826OSQ', false, true, true, false, 'saltar', 'dpa 7', 'origen 6', '0', '2021-09-19 15:21:21');

INSERT INTO INFORMACION_BASICA_SOLICITUDES(NOMBRE_BENEFICIARIO, CURP_BENEFICIARIO, ID_SOLICITUD, URGENTE, NUEVO, VULNERABLE, PENDIENTE, SOLICITUD_NOMBRE, DEPARTAMENTO, ORIGEN, AVANCE_SOLICITUD, FECHA)
VALUES ('RAQUEL CARO DE JUAN', '52481964N', '4129NPK', false, true, false, true, 'saltar', 'dpa 7', 'origen 6', '0', '2020-07-31 15:21:21');

INSERT INTO INFORMACION_BASICA_SOLICITUDES(NOMBRE_BENEFICIARIO, CURP_BENEFICIARIO, ID_SOLICITUD, URGENTE, NUEVO, VULNERABLE, PENDIENTE, SOLICITUD_NOMBRE, DEPARTAMENTO, ORIGEN, AVANCE_SOLICITUD, FECHA)
VALUES ('EMILIO LEDESMA CANDELA', '73475632Q', '3458NBU', false, false, false, true, 'morder', 'dpa 8', 'origen 7', '0','2019-09-27 15:21:21');

INSERT INTO INFORMACION_BASICA_SOLICITUDES(NOMBRE_BENEFICIARIO, CURP_BENEFICIARIO, ID_SOLICITUD, URGENTE, NUEVO, VULNERABLE, PENDIENTE, SOLICITUD_NOMBRE, DEPARTAMENTO, ORIGEN, AVANCE_SOLICITUD, FECHA)
VALUES ('DAVID ESCALONA LASA', '45992549R', '9129RNM', false, false, false, false, 'correr', 'dpa 9', 'origen 8', '0', '2019-12-30 15:21:21');

INSERT INTO INFORMACION_BASICA_SOLICITUDES(NOMBRE_BENEFICIARIO, CURP_BENEFICIARIO, ID_SOLICITUD, URGENTE, NUEVO, VULNERABLE, PENDIENTE, SOLICITUD_NOMBRE, DEPARTAMENTO, ORIGEN, AVANCE_SOLICITUD, FECHA)
VALUES ('MIGUEL ANGEL CARABALLO VAQUERO', '73504062H', '9689PHN', true, false, true, false, 'saludar', 'dpa 10', 'origen 9', '0', '2019-11-15 15:21:21');

INSERT INTO INFORMACION_BASICA_SOLICITUDES(NOMBRE_BENEFICIARIO, CURP_BENEFICIARIO, ID_SOLICITUD, URGENTE, NUEVO, VULNERABLE, PENDIENTE, SOLICITUD_NOMBRE, DEPARTAMENTO, ORIGEN, AVANCE_SOLICITUD, FECHA)
VALUES ('IVAN UTRILLA DUQUE', '97707481P', '1182VEE', false, false, true, true, 'buscar', 'dpa 11', 'origen 10', '0', '2021-01-08 15:21:21');

INSERT INTO INFORMACION_BASICA_SOLICITUDES(NOMBRE_BENEFICIARIO, CURP_BENEFICIARIO, ID_SOLICITUD, URGENTE, NUEVO, VULNERABLE, PENDIENTE, SOLICITUD_NOMBRE, DEPARTAMENTO, ORIGEN, AVANCE_SOLICITUD, FECHA)
VALUES ('MARIA SALMERON MONTEAGUDO', '19642603M', '4808LFX', true, false, false, false, 'trotar', 'dpa 12', 'origen 11', '0', '2020-05-09 15:21:21');

INSERT INTO INFORMACION_BASICA_SOLICITUDES(NOMBRE_BENEFICIARIO, CURP_BENEFICIARIO, ID_SOLICITUD, URGENTE, NUEVO, VULNERABLE, PENDIENTE, SOLICITUD_NOMBRE, DEPARTAMENTO, ORIGEN, AVANCE_SOLICITUD, FECHA)
VALUES ('AURORA MAYA CASELLAS', '02601326A', '4647HQB', true, true, true, true, 'escalar', 'dpa 13', 'origen 12', '0', '2021-03-18 15:21:21');

INSERT INTO INFORMACION_BASICA_SOLICITUDES(NOMBRE_BENEFICIARIO, CURP_BENEFICIARIO, ID_SOLICITUD, URGENTE, NUEVO, VULNERABLE, PENDIENTE, SOLICITUD_NOMBRE, DEPARTAMENTO, ORIGEN, AVANCE_SOLICITUD, FECHA)
VALUES ('PABLO AMO LACALLE', '82976120D', '0273ISH', false, true, false, false, 'arriba', 'dpa 14', 'origen 13', '0', now());

INSERT INTO INFORMACION_BASICA_SOLICITUDES(NOMBRE_BENEFICIARIO, CURP_BENEFICIARIO, ID_SOLICITUD, URGENTE, NUEVO, VULNERABLE, PENDIENTE, SOLICITUD_NOMBRE, DEPARTAMENTO, ORIGEN, AVANCE_SOLICITUD, FECHA)
VALUES ('SAMUEL JULIA ARIZA', '45430678C', '8087ZIU', false, false, false, false, 'abajo', 'dpa 15', 'origen 14', '0', '2017-03-01 15:21:21');

INSERT INTO INFORMACION_BASICA_SOLICITUDES(NOMBRE_BENEFICIARIO, CURP_BENEFICIARIO, ID_SOLICITUD, URGENTE, NUEVO, VULNERABLE, PENDIENTE, SOLICITUD_NOMBRE, DEPARTAMENTO, ORIGEN, AVANCE_SOLICITUD, FECHA)
VALUES ('MONTSERRAT RUBIA TOSCANO', '63025886K', '9733UWJ', false, false, true, false, 'izquierda', 'dpa 16', 'origen 15', '0','2021-11-05 15:21:21');

INSERT INTO INFORMACION_BASICA_SOLICITUDES(NOMBRE_BENEFICIARIO, CURP_BENEFICIARIO, ID_SOLICITUD, URGENTE, NUEVO, VULNERABLE, PENDIENTE, SOLICITUD_NOMBRE, DEPARTAMENTO, ORIGEN, AVANCE_SOLICITUD, FECHA)
VALUES ('ENCARNACION ARANGO MAESO', '83714170N', '1555HJY', true, false, false, true, 'derecha', 'dpa 17', 'origen 16', '0', '2019-12-31 15:21:21');

INSERT INTO INFORMACION_BASICA_SOLICITUDES(NOMBRE_BENEFICIARIO, CURP_BENEFICIARIO, ID_SOLICITUD, URGENTE, NUEVO, VULNERABLE, PENDIENTE, SOLICITUD_NOMBRE, DEPARTAMENTO, ORIGEN, AVANCE_SOLICITUD, FECHA)
VALUES ('JOSE ANGEL PALENCIA BLAS', '31989592L', '0916CBM', false, true, false, true, 'agacharse', 'dpa 18', 'origen 17', '0', '2021-07-24 15:21:21');

INSERT INTO INFORMACION_BASICA_SOLICITUDES(NOMBRE_BENEFICIARIO, CURP_BENEFICIARIO, ID_SOLICITUD, URGENTE, NUEVO, VULNERABLE, PENDIENTE, SOLICITUD_NOMBRE, DEPARTAMENTO, ORIGEN, AVANCE_SOLICITUD, FECHA)
VALUES ('JULIAN OÑATE QUILEZ', '99368793F', '8880QZQ', true, true, true, false, 'rotar', 'dpa 19', 'origen 18', '0', '2020-04-16 15:21:21');

INSERT INTO INFORMACION_BASICA_SOLICITUDES(NOMBRE_BENEFICIARIO, CURP_BENEFICIARIO, ID_SOLICITUD, URGENTE, NUEVO, VULNERABLE, PENDIENTE, SOLICITUD_NOMBRE, DEPARTAMENTO, ORIGEN, AVANCE_SOLICITUD, FECHA)
VALUES ('ANA BELEN FERRANDO QUINTANA', '43947476L', '3236KWT', false, true, false, true, 'rodar', 'dpa 20', 'origen 18', '0', '2020-06-03 15:21:21');

INSERT INTO INFORMACION_BASICA_SOLICITUDES(NOMBRE_BENEFICIARIO, CURP_BENEFICIARIO, ID_SOLICITUD, URGENTE, NUEVO, VULNERABLE, PENDIENTE, SOLICITUD_NOMBRE, DEPARTAMENTO, ORIGEN, AVANCE_SOLICITUD, FECHA)
VALUES ('ALFREDO GALDON RUIZ', '99871956E', '8410JCR', true, true, false, true, 'leer', 'dpa 21', 'origen 19', '0', '2021-12-03 15:21:21');

INSERT INTO INFORMACION_BASICA_SOLICITUDES(NOMBRE_BENEFICIARIO, CURP_BENEFICIARIO, ID_SOLICITUD, URGENTE, NUEVO, VULNERABLE, PENDIENTE, SOLICITUD_NOMBRE, DEPARTAMENTO, ORIGEN, AVANCE_SOLICITUD, FECHA)
VALUES ('ALFONSO BELLVER DIALLO', '21053329A', '3958HLP', true, true, true, false, 'gritar', 'dpa 22', 'origen 20', '0', '2021-09-08 15:21:21');