#DROP TABLE REGISTRADOS_PROGRAMA;

CREATE TABLE IF NOT EXISTS REGISTRADOS_PROGRAMA(
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    FOLIO VARCHAR(150) NOT NULL,
    PELIGRO VARCHAR(50) NOT NULL,
    NUEVO VARCHAR(50) NOT NULL,
    VULNERABLE VARCHAR(50) NOT NULL,
    ESTADO VARCHAR(50) NOT NULL,
    ORIGEN VARCHAR(200) NOT NULL,
    SOLICITUD VARCHAR(200) NOT NULL,
    EDAD VARCHAR(50) NOT NULL,
    TT VARCHAR(50) NOT NULL,
    BENEFICIARIO VARCHAR(200) NOT NULL,
    TELEFONO VARCHAR(50) NOT NULL,
    COLONIA VARCHAR(200) NOT NULL,
    AFILIACION VARCHAR(200) NOT NULL,
    ZONA VARCHAR(200) NOT NULL,
    PROGRAMA VARCHAR(200) NOT NULL,
    CITA TEXT NOT NULL,
    AVANCE TEXT NOT NULL,
    DIA VARCHAR(5) NOT NULL,
    MES VARCHAR(5) NOT NULL,
	YEAR_FECHA VARCHAR(5) NOT NULL,
    FECHA DATETIME NOT NULL
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS REGISTRADOS_PROGRAMA(
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    FOLIO VARCHAR(150) NOT NULL,
    PELIGRO VARCHAR(50) NOT NULL,
    NUEVO VARCHAR(50) NOT NULL,
    VULNERABLE VARCHAR(50) NOT NULL,
    ESTADO VARCHAR(50) NOT NULL,
    ORIGEN VARCHAR(200) NOT NULL,
    SOLICITUD VARCHAR(200) NOT NULL,
    EDAD VARCHAR(50) NOT NULL,
    TT VARCHAR(50) NOT NULL,
    CURP_BENEFICIARIO VARCHAR(200) NOT NULL,
    BENEFICIARIO VARCHAR(200) NOT NULL,
    TELEFONO VARCHAR(50) NOT NULL,
    COLONIA VARCHAR(200) NOT NULL,
    AFILIACION VARCHAR(200) NOT NULL,
    ZONA VARCHAR(200) NOT NULL,
	ID_PROGRAMA VARCHAR(200) NOT NULL,
    PROGRAMA VARCHAR(200) NOT NULL,
    CITA TEXT NOT NULL,
    AVANCE TEXT NOT NULL,
    DIA VARCHAR(5) NOT NULL,
    MES VARCHAR(5) NOT NULL,
	YEAR_FECHA VARCHAR(5) NOT NULL,
    FECHA DATETIME NOT NULL
)ENGINE=INNODB;

INSERT INTO REGISTRADOS_PROGRAMA(FOLIO, PELIGRO, NUEVO, VULNERABLE, ESTADO, ORIGEN, SOLICITUD, EDAD, TT, BENEFICIARIO, TELEFONO, COLONIA, AFILIACION, ZONA, PROGRAMA, CITA, AVANCE, DIA, MES, YEAR_FECHA, FECHA)
VALUES('31b7j', 'si', 'si', 'si', 'no', 'CIUD', 'ADULTO MAYOR', '76', 'TT', 'MARTINEZ PEREZ JUAN', '7295543232', 'BELL', 'SC09', '05', 'CASA', 'NADA POR AQUI', 'SIN AVANCE', '23', '09', '2021', now());

INSERT INTO REGISTRADOS_PROGRAMA(FOLIO, PELIGRO, NUEVO, VULNERABLE, ESTADO, ORIGEN, SOLICITUD, EDAD, TT, BENEFICIARIO, TELEFONO, COLONIA, AFILIACION, ZONA, PROGRAMA, CITA, AVANCE, DIA, MES, YEAR_FECHA, FECHA)
VALUES('15hu6', 'no', 'si', 'no', 'no', 'CIUD', 'ADULTO MAYOR', '69', 'TT', 'LOPEZ SANCHEZ PEREZ', '7224344443', 'BELL', 'SC09', '05', 'CASA', 'NADA POR AQUI', 'SIN AVANCE', '15', '06', '2021', '2021-06-24 13:05:11');

#TODOS
SELECT * FROM REGISTRADOS_PROGRAMA;

#EL LOS DE ESTE MES
SELECT * FROM REGISTRADOS_PROGRAMA WHERE YEAR(FECHA) = YEAR(CURRENT_DATE()) AND MONTH(FECHA) = MONTH(CURRENT_DATE());

#EL DE ESTA SEMANA
SELECT * FROM REGISTRADOS_PROGRAMA WHERE YEAR(FECHA) = YEAR(CURRENT_DATE()) AND WEEK(FECHA) = WEEK(CURRENT_DATE());

#LOS DE HOY
SELECT * FROM REGISTRADOS_PROGRAMA WHERE YEAR(FECHA) = YEAR(CURRENT_DATE()) AND WEEK(FECHA) = WEEK(CURRENT_DATE()) AND DAY(FECHA) = DAY(CURRENT_DATE());