#DROP TABLE INFORMACION_BASICA_SOLICITUDES;
#DROP TABLE INFORMACION_BASICA_DOCUMENTOS;
#DROP TABLE INFORMACION_BASICA_NOTAS;

# Tabla SOLICITUDES
CREATE TABLE IF NOT EXISTS INFORMACION_BASICA_SOLICITUDES(
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOMBRE_BENEFICIARIO VARCHAR(200) NOT NULL,
    CURP_BENEFICIARIO VARCHAR(55) NOT NULL,
    ID_SOLICITUD VARCHAR(50) NOT NULL,
    URGENTE BOOLEAN NOT NULL,
    NUEVO BOOLEAN NOT NULL,
    VULNERABLE BOOLEAN NOT NULL,
    PENDIENTE BOOLEAN NOT NULL,
    SOLICITUD_NOMBRE VARCHAR(200) NOT NULL,
    DEPARTAMENTO VARCHAR(200) NOT NULL,
    ORIGEN VARCHAR(200) NOT NULL,
    AVANCE_SOLICITUD VARCHAR(10) NOT NULL,
    FECHA DATETIME NOT NULL
)ENGINE=INNODB;

# Tabla DOCUMENTOS
CREATE TABLE IF NOT EXISTS INFORMACION_BASICA_DOCUMENTOS(
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOM_EN_SERVIDOR VARCHAR(250) NOT NULL,
    NOM_EN_PANTALLA VARCHAR(250) NOT NULL,
    EXTENSION VARCHAR(10) NOT NULL,
    ID_PROPIETARIO INT NOT NULL,
    FECHA DATETIME NOT NULL
)ENGINE=INNODB;

# Tabla para NOTAS
CREATE TABLE IF NOT EXISTS INFORMACION_BASICA_NOTAS(
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    ID_SOLICITUD_PROPIETARIA INT NOT NULL,
    FECHA DATETIME NOT NULL,
    NOTA TEXT NOT NULL
)ENGINE=INNODB;

# Tabla de PROGRAMAS
CREATE TABLE IF NOT EXISTS INFORMACION_BASICA_PROGRAMAS(
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    ID_PROGRAMA VARCHAR(50) NOT NULL,
    NOMBRE_PROGRAMA VARCHAR(255) NOT NULL
)ENGINE=INNODB;